### ISSUE TITLE
Dash associated to specific button rather than mapped Ping button.

### ISSUE THREAD

**Issue by Sempiternity87** [propstg/plateup-dash-ping#2]
Looks like this is specifying a specific button, when it's intended to be the same button as the Ping. Since players can remap the controls to different buttons, this should use the mapping, or have a way of creating a new mapping (not sure if the latter is possible).
https://github.com/propstg/plateup-dash-ping/blob/726adbfac600b713babbab1a02ba618d105d6897/DashPing/Main.cs#L51

**Comment by propstg** [comment]
Hey @Sempiternity87, thanks for the report. I just pushed an update here and to the workshop that should hopefully address this.

It now looks at each player's own input device for the `SecondaryAction2` button using the game's controller logic, which means it should work for different controllers (`Joystick1Button1` mapped to a different button entirely on PS controllers :D), follows remapping made through the game, and works independently for multiple local players.
