### ISSUE TITLE
Set initial speed at the start of each dash instead of using a static value

### ISSUE THREAD

**Issue by Jasonleh99** [propstg/plateup-dash-ping#4]
Hi! there's another incompatibility issue with PrepGhost after fixing the one posted up on the github
See Context: https://github.com/Jasonleh99/PlateupPrepGhost/issues/10

This could be fixed by grabbing the InitialSpeed at the start of each dash and changing the dash speed to a 2.0 multiplier to be multiplied by InitialSpeed during the dash period. This could also become buggy with too many speed-adjusting mods, so I also think that it would be fine to leave implementation as is as the issue shouldn't have too much of an impact on users.

**Comment by propstg** [comment]
Hey! That makes sense. I think I might just disable dashing during the prep phase when both mods are installed. The constant speed increase is probably more useful than dashing, during prep. I'll try to get a release with that out in the next day or two.

Thank you!

**Comment by propstg** [comment]
A fix for this has been released. If the speed is not equal to 3000 when dash is requested, no dashing will take place. Thanks!
